version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run:
          name: Show the current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
